slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # 地图参数
    resolution: 0.05
    map_update_interval: 1.0

    # 激光滤波与频率
    max_laser_range: 8.0
    minimum_time_interval: 0.1

    # 位姿估计
    transform_publish_period: 0.05
    publish_map_period: 1.0
    use_scan_matching: true
    scan_matcher_translation_weight: 20.0
    scan_matcher_rotation_weight: 10.0

    # 后端图优化
    use_pose_graph: true
    pose_graph_optimizer: g2o
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.174
    optimization_interval: 10.0

    # 启用回环闭环检测
    use_loop_closing: true
    loop_match_min_chain_size: 10
    loop_match_max_variance: 1.0
    loop_search_max_distance: 3.0

    # 优化器设置
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_max_num_iterations: 200
