controller_manager:
  ros__parameters:
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["left wheel motor"]
    right_wheel_names: ["right wheel motor"]

    wheel_separation: 0.16
    wheel_radius: 0.033

    # The real separation between wheels is not resulting in a perfect odometry
    wheel_separation_multiplier: 1.112

    use_stamped_vel: false
    base_frame_id: "base_link"
    
    linear:
      x:
        max_velocity: 0.2 # Maximal speed of turtlebot

joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - LDS-01_secondary_motor
      - LDS-01_main_motor
      - base_link_compass_joint
      - base_link_gyro_joint
      - base_link_accelerometer_joint
      - base_link_LDS-01_joint
      - LDS-01_screw3_joint
      - LDS-01_screw2_joint
      - LDS-01_screw1_joint
      - LDS-01_screw0_joint
      - base_link_inertial_unit_joint
      - base_link_gps_joint
      - base_link_imu_link_joint
      - base_link_Velodyne HDL-64E_joint
      - Velodyne HDL-64E_solid_0_joint
